source("./covid19/deu/sn/common.r")

source("./covid19/deu/sn/stats.r")
print("----------")
source("./covid19/deu/sn/plot_cmr_ecmr.r")
print("----------")
source("./covid19/deu/sn/plot_ecmr_vaxx.r")
print("----------")
source("./covid19/deu/sn/plot_map_ecmr.r")
print("----------")
source("./covid19/deu/sn/plot_scatter_sign_ecmr.r")
