#!/bin/sh

cd backup
rm -rf *
wget https://s3.mortality.watch/data/mortality/world_fluseason.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_80+.csv
wget https://s3.mortality.watch/data/mortality/world_fluseason_85+.csv
wget https://s3.mortality.watch/data/mortality/world_meta.csv
wget https://s3.mortality.watch/data/mortality/world_midyear.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_80+.csv
wget https://s3.mortality.watch/data/mortality/world_midyear_85+.csv
wget https://s3.mortality.watch/data/mortality/world_monthly.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_80+.csv
wget https://s3.mortality.watch/data/mortality/world_monthly_85+.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_80+.csv
wget https://s3.mortality.watch/data/mortality/world_quarterly_85+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_80+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_104w_sma_85+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_80+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_13w_sma_85+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_80+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_26w_sma_85+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_80+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_52w_sma_85+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_80+.csv
wget https://s3.mortality.watch/data/mortality/world_weekly_85+.csv
wget https://s3.mortality.watch/data/mortality/world_yearly.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_0-14.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_0-24.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_0-29.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_0-64.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_0-9.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_10-19.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_15-64.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_20-29.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_25-44.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_30-39.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_30-44.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_40-49.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_45-64.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_50-59.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_60-69.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_65-74.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_70-79.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_75-84.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_80+.csv
wget https://s3.mortality.watch/data/mortality/world_yearly_85+.csv